1. Подберите скорость обучения (alpha) и количество итераций:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [3]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])
X.shape

(2, 10)

In [4]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [5]:
n = X.shape[1]
alpha = 1e-4
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.0001)

In [6]:
y_pred = np.dot(W, X)
y_pred

array([1.5, 1.5, 2. , 1.5, 2.5, 1. , 3.5, 6. , 1.5, 2. ])

In [7]:
for i in range(1000):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
        if i % 100 == 0:
            print(i, W, err)

0 [1.01102 0.5    ] 3173.15
0 [1.01102 0.534  ] 3173.15
100 [2.02168794 3.42791095] 2207.6942101483005
100 [2.02168794 3.452835  ] 2207.6942101483005
200 [2.88306663 5.57141207] 1670.7027004086372
200 [2.88306663 5.58962851] 1670.7027004086372
300 [3.63289519 7.1352209 ] 1368.0832412796256
300 [3.63289519 7.14848061] 1368.0832412796256
400 [4.29908617 8.27068189] 1193.7493344933293
400 [4.29908617 8.28027926] 1193.7493344933293
500 [4.90228732 9.08968104] 1089.714750358689
500 [4.90228732 9.09657298] 1089.714750358689
600 [5.45777535 9.6749329 ] 1024.2828984889416
600 [5.45777535 9.67982684] 1024.2828984889416
700 [ 5.97685612 10.08758579] 980.1260644155933
700 [ 5.97685612 10.0910047 ] 980.1260644155933
800 [ 6.46789973 10.37284419] 947.770026039189
800 [ 6.46789973 10.37517467] 947.770026039189
900 [ 6.93710574 10.56412541] 922.0330206910178
900 [ 6.93710574 10.56565326] 922.0330206910178


In [8]:
n = X.shape[1]
alpha = 0.045
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.045)

In [9]:
for i in range(160):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
        if i % 10 == 0:
            print(i, W, err)

0 [5.959 0.5  ] 3173.15
0 [ 5.959 15.8  ] 3173.15
10 [21.20067617  8.95319417] 446.89145560316894
10 [21.20067617  8.7177681 ] 446.89145560316894
20 [31.11142172  7.03365132] 199.7052622577388
20 [31.11142172  6.88752877] 199.7052622577388
30 [37.24894076  5.84467936] 104.90817361421769
30 [37.24894076  5.75418892] 104.90817361421769
40 [41.04976906  5.10837561] 68.55303589292456
40 [41.04976906  5.0523369 ] 68.55303589292456
50 [43.40353702  4.65239916] 54.61066637876841
50 [43.40353702  4.61769564] 54.61066637876841
60 [44.86117288  4.37002314] 49.26370086430646
60 [44.86117288  4.34853203] 49.26370086430646
70 [45.76385417  4.19515399] 47.213113969172376
70 [45.76385417  4.18184502] 47.213113969172376
80 [46.32286451  4.08686143] 46.42670406936606
80 [46.32286451  4.07861949] 46.42670406936606
90 [46.66904711  4.01979827] 46.12511210465544
90 [46.66904711  4.01469422] 46.12511210465544
100 [46.88343025  3.97826756] 46.00945014109114
100 [46.88343025  3.97510674] 46.00945014109114
11

*2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

In [10]:
n = X.shape[1]
alpha = 0.045
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.045)

In [11]:
for i in range(160):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
    W -= (alpha * (1/n * 2 * np.dot(X, (y_pred - y))))
    if i % 10 == 0:
        print(i, W, err)

0 [ 5.959 15.8  ] 3173.15
10 [21.20067617  8.7177681 ] 446.89145560316894
20 [31.11142172  6.88752877] 199.70526225773878
30 [37.24894076  5.75418892] 104.90817361421769
40 [41.04976906  5.0523369 ] 68.55303589292456
50 [43.40353702  4.61769564] 54.61066637876841
60 [44.86117288  4.34853203] 49.26370086430646
70 [45.76385417  4.18184502] 47.213113969172376
80 [46.32286451  4.07861949] 46.42670406936606
90 [46.66904711  4.01469422] 46.12511210465544
100 [46.88343025  3.97510674] 46.00945014109114
110 [47.01619294  3.95059109] 45.96509322386228
120 [47.0984099  3.9354091] 45.94808213356594
130 [47.14932503  3.92600723] 45.94155829892754
140 [47.18085563  3.92018486] 45.93905637708432
150 [47.20038182  3.9165792 ] 45.93809687806932


In [12]:
import time

In [13]:
n = X.shape[1]
alpha = 0.045
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.045)

In [14]:
start_time = time.time()
for i in range(160):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
        if i % 10 == 0:
            print(i, W, err)
t1 = time.time() - start_time

0 [5.959 0.5  ] 3173.15
0 [ 5.959 15.8  ] 3173.15
10 [21.20067617  8.95319417] 446.89145560316894
10 [21.20067617  8.7177681 ] 446.89145560316894
20 [31.11142172  7.03365132] 199.7052622577388
20 [31.11142172  6.88752877] 199.7052622577388
30 [37.24894076  5.84467936] 104.90817361421769
30 [37.24894076  5.75418892] 104.90817361421769
40 [41.04976906  5.10837561] 68.55303589292456
40 [41.04976906  5.0523369 ] 68.55303589292456
50 [43.40353702  4.65239916] 54.61066637876841
50 [43.40353702  4.61769564] 54.61066637876841
60 [44.86117288  4.37002314] 49.26370086430646
60 [44.86117288  4.34853203] 49.26370086430646
70 [45.76385417  4.19515399] 47.213113969172376
70 [45.76385417  4.18184502] 47.213113969172376
80 [46.32286451  4.08686143] 46.42670406936606
80 [46.32286451  4.07861949] 46.42670406936606
90 [46.66904711  4.01979827] 46.12511210465544
90 [46.66904711  4.01469422] 46.12511210465544
100 [46.88343025  3.97826756] 46.00945014109114
100 [46.88343025  3.97510674] 46.00945014109114
11

In [15]:
start_time = time.time()
for i in range(160):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
    W -= (alpha * (1/n * 2 * np.dot(X, (y_pred - y))))
    if i % 10 == 0:
        print(i, W, err)
t2 = time.time() - start_time

0 [47.21247396  3.9143463 ] 45.93772890559957
10 [47.21996235  3.91296351] 45.937587786394246
20 [47.22459974  3.91210718] 45.937533666502844
30 [47.22747157  3.91157687] 45.93751291126516
40 [47.22925004  3.91124847] 45.937504951532055
50 [47.2303514   3.91104509] 45.937501898936276
60 [47.23103345  3.91091915] 45.937500728251145
70 [47.23145582  3.91084115] 45.93750027928782
80 [47.23171739  3.91079285] 45.93750010710819
90 [47.23187938  3.91076294] 45.93750004107652
100 [47.23197969  3.91074442] 45.93750001575306
110 [47.23204181  3.91073294] 45.93750000604139
120 [47.23208028  3.91072584] 45.93750000231688
130 [47.23210411  3.91072144] 45.93750000088854
140 [47.23211886  3.91071872] 45.937500000340734
150 [47.232128    3.91071703] 45.93750000013067


In [16]:
t2 < t1 

True