In [150]:
import numpy as np

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

## Часть 1.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение__

а)

$A\times B$ - не определено

$B\times A$ - не определено

б)

$A\times B$ - определено, размерность - $ 2\times 3$ 

$B\times A$ - не определено

в)

$A\times B$ - определено, размерность - $ 8\times 8$ 

$B\times A$ - определено, размерность - $ 3\times 3$ 

г)

$A\times B$ - определено, размерность - $ 4\times 4$ 

$B\times A$ - определено, размерность - $ 4\times 4$ 

___

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение__

In [195]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

In [196]:
sum_a_b = np.ones((2,2))

In [197]:
sum_a_b[0][0] = a[0][0] + b[0][0]
sum_a_b[0][1] = a[0][1] + b[0][1]
sum_a_b[1][0] = a[1][0] + b[1][0]
sum_a_b[1][1] = a[1][1] + b[1][1]
sum_a_b

array([[ 5., -3.],
       [ 3.,  5.]])

In [198]:
a + b

array([[ 5, -3],
       [ 3,  5]])

In [199]:
mult_a_b = np.ones((2,2))

In [200]:
mult_a_b[0][0] = a[0][0] * b[0][0] + a[0][1] * b[1][0]
mult_a_b[0][1] = a[0][0] * b[0][1] + a[0][1] * b[1][1]
mult_a_b[1][0] = a[1][0] * b[0][0] + a[1][1] * b[1][0]
mult_a_b[1][1] = a[1][0] * b[0][1] + a[1][1] * b[1][1]
mult_a_b

array([[  4., -11.],
       [ 12.,  -3.]])

In [201]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

___

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение__

In [202]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

In [203]:
linear_comb = np.ones((2, 2))

In [204]:
linear_comb[0][0] = 3 * a[0][0] + (-2) * b[0][0] + 4 * c[0][0]
linear_comb[0][1] = 3 * a[0][1] + (-2) * b[0][1] + 4 * c[0][1]
linear_comb[1][0] = 3 * a[1][0] + (-2) * b[1][0] + 4 * c[1][0]
linear_comb[1][1] = 3 * a[1][1] + (-2) * b[1][1] + 4 * c[1][1]
linear_comb

array([[ 11.,  -5.],
       [  9., -12.]])

In [205]:
3 * a - 2 * b + 4 * c

array([[ 11,  -5],
       [  9, -12]])

___

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__Решение__

In [206]:
a = np.array([[4, 1], [5, -2], [2, 3]])

In [207]:
a_t = np.ones((2, 3))

In [208]:
a_t[0][0] = a[0][0]
a_t[0][1] = a[1][0]
a_t[0][2] = a[2][0]
a_t[1][0] = a[0][1]
a_t[1][1] = a[1][1]
a_t[1][2] = a[2][1]
a_t

array([[ 4.,  5.,  2.],
       [ 1., -2.,  3.]])

In [209]:
a.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [210]:
a_a_t = np.ones((3, 3))

In [211]:
a_a_t[0][0] = a[0][0] * a_t[0][0] + a[0][1] * a_t[1][0]
a_a_t[0][1] = a[0][0] * a_t[0][1] + a[0][1] * a_t[1][1]
a_a_t[0][2] = a[0][0] * a_t[0][2] + a[0][1] * a_t[1][2]
a_a_t[1][0] = a[1][0] * a_t[0][0] + a[1][1] * a_t[1][0]
a_a_t[1][1] = a[1][0] * a_t[0][1] + a[1][1] * a_t[1][1]
a_a_t[1][2] = a[1][0] * a_t[0][2] + a[1][1] * a_t[1][2]
a_a_t[2][0] = a[2][0] * a_t[0][0] + a[2][1] * a_t[1][0]
a_a_t[2][1] = a[2][0] * a_t[0][1] + a[2][1] * a_t[1][1]
a_a_t[2][2] = a[2][0] * a_t[0][2] + a[2][1] * a_t[1][2]
a_a_t


array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [212]:
np.dot(a, a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [213]:
a_t_a = np.ones((2, 2))

In [214]:
a_t_a[0][0] = a_t[0][0] * a[0][0] + a_t[0][1] * a[1][0] + a_t[0][2] * a[2][0]
a_t_a[0][1] = a_t[0][0] * a[0][1] + a_t[0][1] * a[1][1] + a_t[0][2] * a[2][1]
a_t_a[1][0] = a_t[1][0] * a[0][0] + a_t[1][1] * a[1][0] + a_t[1][2] * a[2][0]
a_t_a[1][1] = a_t[1][0] * a[0][1] + a_t[1][1] * a[1][1] + a_t[1][2] * a[2][1]
a_t_a

array([[45.,  0.],
       [ 0., 14.]])

In [215]:
np.dot(a.T, a)

array([[45,  0],
       [ 0, 14]])

## Часть 2.

__1.__ Вычислить определитель:

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

   б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$
    
   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

__Решение__

а)

$sinx\cdot sinx - (-cosx\cdot cosx) = sin^2x+cos^2x=1$

б)

In [216]:
4*5*9 #т.к. матрица треугольного вида

180

In [217]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(a)

180.0

в)

In [218]:
det = 1*(5*9-6*8) - 2*(4*9-7*6) + 3*(4*8-5*7)
det

0

In [219]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(a)

6.66133814775094e-16

___

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение__

а)

$det(A^2)=det(A\cdot A)=detA\cdot detA=4\cdot 4=16$

б)

$det(A^T)=det(A)=4$

в)

Тут необходимо знать порядок матрицы, т.к. если мы всю матрицу умножаем на 2, а такого прямого свойства определителя нет, то, например, для матрицы 2-го порядка это значит, что мы две строки умножили на 2, поэтому определитель в итоге увеличится в 4 раза, а для матрицы 3-го порядка в 8 (согласно свойству о том, что при умножении строки/столбца число, определитель умножается на это же число)

___

__3.__  Доказать, что матрица

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
   
вырожденная.

__Решение__

Матрица вырожденная, если ее определитель равен нулю. 
У нашей матрицы 1 и 2 строки - линейно зависимы (если первую умножить на -2, получим вторую), и, согласно свойству 7 определителя, определитель такой матрицы равен нулю. 

___

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение__

а)

Третья строка - сумма первой и второй, ее можем отбросить. Отняв от второй первую, получим матрицу $\begin{pmatrix}
1 & 2 & 3 \\
0 & -1 & -2 
\end{pmatrix};$ - ранг равен количеству линейно независимых строк, 2.

In [193]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(a)

2

б)

Третья строка - сумма первой и второй, ее можем отбросить. В итоге три линейно независимых строки в матрице, ранг равен 3

In [194]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3